### ISSUE TITLE
Adicionar licença livre

### ISSUE THREAD

**Issue by pizzamaker** [rprata/Driveuino#1]
Faltou especificar no projeto uma licença. Minha sugestão: criar um arquivo de texto tipo COPYING.md ou LICENSE.md com o texto da licença AGPLv3: https://www.gnu.org/licenses/agpl.html

**Comment by rprata** [comment]
Obrigado @pizzamaker. Irei adicionar o CCZero, que é totalmente livre :+1:

**Comment by rprata** [comment]
@pizzamaker, já foi adicionado.
